#!/usr/bin/env php
<?php
require "vendor/autoload.php";

use Constant\Timelog\Command\TimelogCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Debug\ErrorHandler;
use Symfony\Component\Debug\ExceptionHandler;

Debug::enable();
ErrorHandler::register();
ExceptionHandler::register();

$app = new Application('Time Logger', '1.1');
$app->add(new TimelogCommand);
$app->run();